run:
  timeout: 5m

linters:
  enable:
    - govet
    - gofmt
    - unused
    - staticcheck
    - errcheck
    - goconst
    - gosimple

issues:
  exclude-rules:
    - path: test/.*.go
      linters:
        - errcheck
        - goconst
  exclude-use-default: false

